# GitHub Sponsors

github: []

# Open Collective

open_collective: ""

# Ko-fi

ko_fi: ""

# Patreon

patreon: ""

# Buy Me a Coffee

buy_me_a_coffee: ""

# Thanks.dev

thanks_dev: ""

# Community Bridge

community_bridge: ""

# Tidelift

tidelift: ""

# Custom sponsorship URLs

custom: []
